- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  tags:
    - install_docker

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install_docker

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - install_docker

- name: Install Docker
  apt:
    name: "docker-ce"
    state: present
  tags:
    - install_docker

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - manage_docker_service

- name: Add current user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags:
    - configure_docker

- name: Configure Docker Daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart Docker
  tags:
    - configure_docker

- name: Start Docker containers
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    ports: "{{ item.ports | default([]) }}"
    volumes: "{{ item.volumes | default([]) }}"
    state: started
  loop: "{{ docker_containers }}"
  tags:
    - manage_containers